@switch(session('locale'))
    @case('en')
    <select id="known_languages" name="known_languages[]" class="form-control" data-language="en" multiple>
        <option value="">Select or search for language(s)...</option>
        <option value="af">Afrikaans</option>
        <option value="sq">Albanian - shqip</option>
        <option value="am">Amharic - አማርኛ</option>
        <option value="ar">Arabic - العربية</option>
        <option value="an">Aragonese - aragonés</option>
        <option value="hy">Armenian - հայերեն</option>
        <option value="ast">Asturian - asturianu</option>
        <option value="az">Azerbaijani - azərbaycan dili</option>
        <option value="eu">Basque - euskara</option>
        <option value="be">Belarusian - беларуская</option>
        <option value="bn">Bengali - বাংলা</option>
        <option value="bs">Bosnian - bosanski</option>
        <option value="br">Breton - brezhoneg</option>
        <option value="bg">Bulgarian - български</option>
        <option value="ca">Catalan - català</option>
        <option value="zh">Chinese - 中文</option>
        <option value="hr">Croatian - hrvatski</option>
        <option value="cs">Czech - čeština</option>
        <option value="da">Danish - dansk</option>
        <option value="nl">Dutch - Nederlands</option>
        <option value="en">English</option>
        <option value="eo">Esperanto - esperanto</option>
        <option value="et">Estonian - eesti</option>
        <option value="fo">Faroese - føroyskt</option>
        <option value="fil">Filipino</option>
        <option value="fi">Finnish - suomi</option>
        <option value="fr">French - français</option>
        <option value="gl">Galician - galego</option>
        <option value="ka">Georgian - ქართული</option>
        <option value="de">German - Deutsch</option>
        <option value="el">Greek - Ελληνικά</option>
        <option value="gn">Guarani</option>
        <option value="gu">Gujarati - ગુજરાતી</option>
        <option value="ha">Hausa</option>
        <option value="he">Hebrew - עברית</option>
        <option value="hi">Hindi - हिन्दी</option>
        <option value="hu">Hungarian - magyar</option>
        <option value="is">Icelandic - íslenska</option>
        <option value="id">Indonesian - Indonesia</option>
        <option value="ia">Interlingua</option>
        <option value="ga">Irish - Gaeilge</option>
        <option value="it">Italian - italiano</option>
        <option value="ja">Japanese - 日本語</option>
        <option value="kn">Kannada - ಕನ್ನಡ</option>
        <option value="kk">Kazakh - қазақ тілі</option>
        <option value="km">Khmer - ខ្មែរ</option>
        <option value="ko">Korean - 한국어</option>
        <option value="ku">Kurdish - Kurdî</option>
        <option value="ky">Kyrgyz - кыргызча</option>
        <option value="lo">Lao - ລາວ</option>
        <option value="lv">Latvian - latviešu</option>
        <option value="ln">Lingala - lingála</option>
        <option value="lt">Lithuanian - lietuvių</option>
        <option value="mk">Macedonian - македонски</option>
        <option value="ms">Malay - Bahasa Melayu</option>
        <option value="ml">Malayalam - മലയാളം</option>
        <option value="mt">Maltese - Malti</option>
        <option value="mr">Marathi - मराठी</option>
        <option value="mn">Mongolian - монгол</option>
        <option value="ne">Nepali - नेपाली</option>
        <option value="no">Norwegian - norsk</option>
        <option value="or">Oriya - ଓଡ଼ିଆ</option>
        <option value="om">Oromo - Oromoo</option>
        <option value="ps">Pashto - پښتو</option>
        <option value="fa">Persian - فارسی</option>
        <option value="pl">Polish - polski</option>
        <option value="pt">Portuguese - português</option>
        <option value="pa">Punjabi - ਪੰਜਾਬੀ</option>
        <option value="qu">Quechua</option>
        <option value="ro">Romanian - română</option>
        <option value="rm">Romansh - rumantsch</option>
        <option value="ru">Russian - русский</option>
        <option value="sr">Serbian - српски</option>
        <option value="sn">Shona - chiShona</option>
        <option value="sd">Sindhi</option>
        <option value="si">Sinhala - සිංහල</option>
        <option value="sk">Slovak - slovenčina</option>
        <option value="sl">Slovenian - slovenščina</option>
        <option value="so">Somali - Soomaali</option>
        <option value="st">Southern Sotho</option>
        <option value="es">Spanish - español</option>
        <option value="su">Sundanese</option>
        <option value="sw">Swahili - Kiswahili</option>
        <option value="sv">Swedish - svenska</option>
        <option value="tg">Tajik - тоҷикӣ</option>
        <option value="ta">Tamil - தமிழ்</option>
        <option value="tt">Tatar</option>
        <option value="te">Telugu - తెలుగు</option>
        <option value="th">Thai - ไทย</option>
        <option value="ti">Tigrinya - ትግርኛ</option>
        <option value="to">Tongan - lea fakatonga</option>
        <option value="tr">Turkish - Türkçe</option>
        <option value="tk">Turkmen</option>
        <option value="uk">Ukrainian - українська</option>
        <option value="ur">Urdu - اردو</option>
        <option value="ug">Uyghur</option>
        <option value="uz">Uzbek - o‘zbek</option>
        <option value="vi">Vietnamese - Tiếng Việt</option>
        <option value="wa">Walloon - wa</option>
        <option value="cy">Welsh - Cymraeg</option>
        <option value="xh">Xhosa</option>
        <option value="yi">Yiddish</option>
        <option value="yo">Yoruba - Èdè Yorùbá</option>
        <option value="zu">Zulu - isiZulu</option>
    </select>
    @break

    @case('pl')
    <select id="known_languages" name="known_languages[]" class="form-control" data-language="pl" multiple>
        <option value="">Wybierz lub wyszukaj język(i)...</option>
        <option value="af">Afrykanerski - Afrikaans</option>
        <option value="sq">Albański - shqip</option>
        <option value="am">Amharski – አማርኛ</option>
        <option value="ar">Arabski – العربية</option>
        <option value="an">Aragoński - aragonés</option>
        <option value="hy">Ormiański – հայերեն</option>
        <option value="ast">Asturyjski - asturianu</option>
        <option value="az">Azerbejdżański - azərbaycan dili</option>
        <option value="eu">Baskijski - euskara</option>
        <option value="be">Białoruski - беларуская</option>
        <option value="bn">Bengalski - বাংলা</option>
        <option value="bs">Bośniacki - bosanski</option>
        <option value="br">Breton - brezhoneg</option>
        <option value="bg">Bułgarski - български</option>
        <option value="ca">Kataloński - català</option>
        <option value="zh">Chiński – 中文</option>
        <option value="hr">Chorwacki - hrvatski</option>
        <option value="cs">Czeski - czeski</option>
        <option value="da">Duński - duński</option>
        <option value="nl">Holenderski – holenderski</option>
        <option value="en">Angielski - English</option>
        <option value="eo">Esperanto</option>
        <option value="et">Estoński - eesti</option>
        <option value="fo">Farerski - føroyskt</option>
        <option value="fil">Filipiński - filipino</option>
        <option value="fi">Fiński – suomi</option>
        <option value="fr">Francuski – francuski</option>
        <option value="gl">Galicyjski - galego</option>
        <option value="ka">Gruziński - ქართული</option>
        <option value="de">Niemiecki - Deutsch</option>
        <option value="el">Grecki - Ελληνικά</option>
        <option value="gn">Guarani</option>
        <option value="gu">Gudżarati - ગુજરાતી</option>
        <option value="ha">Hausa</option>
        <option value="he">Hebrajski - עברית</option>
        <option value="hi">Hindi - हिन्दी</option>
        <option value="hu">Węgierski - magyar</option>
        <option value="is">Islandzki - íslenska</option>
        <option value="id">Indonezyjski – Indonezja</option>
        <option value="ia">Interlingua</option>
        <option value="ga">Irlandzki – Gaeilge</option>
        <option value="it">Włoski - włoski</option>
        <option value="ja">Japoński – 日本語</option>
        <option value="kn">Kannada - ಕನ್ನಡ</option>
        <option value="kk">kazachski - азақ тілі</option>
        <option value="km">Khmer - ខ្មែរ</option>
        <option value="ko">Koreański - 한국어</option>
        <option value="ku">Kurdyjski – Kurdî</option>
        <option value="ky">Kirgiski - кыргызча</option>
        <option value="lo">Lao - ລາວ</option>
        <option value="lv">Łotewski - latviešu</option>
        <option value="ln">Lingala - lingála</option>
        <option value="lt">Litewski - lietuvių</option>
        <option value="mk">Macedoński – македонски</option>
        <option value="ms">Malajski – Bahasa Melayu</option>
        <option value="ml">Malajalam – മലയാളം</option>
        <option value="mt">Maltański – Malti</option>
        <option value="mr">Marathi - मराठी</option>
        <option value="mn">mongolski - монгол</option>
        <option value="ne">Nepalski – नेपाली</option>
        <option value="no">Norweski - norsk</option>
        <option value="or">Oriya - ଓଡ଼ିଆ</option>
        <option value="om">Oromo - Oromoo</option>
        <option value="ps">Paszto - پښتو</option>
        <option value="fa">perski - فارسی</option>
        <option value="pl">Polski</option>
        <option value="pt">Portugalski – português</option>
        <option value="pa">pendżabski – ਪੰਜਾਬੀ</option>
        <option value="qu">Quechua</option>
        <option value="ro">Rumuński - română</option>
        <option value="rm">Romański - rumantsch</option>
        <option value="ru">Rosyjski – русский</option>
        <option value="sr">serbski - српски</option>
        <option value="sn">Shona - chiShona</option>
        <option value="sd">Sindhi</option>
        <option value="si">Singhala - සිංහල</option>
        <option value="sk">Słowacki - Slovenčina</option>
        <option value="sl">Słoweński - Slovenščina</option>
        <option value="so">somalijski – soomaali</option>
        <option value="st">Południowe Sotho</option>
        <option value="es">Hiszpański - español</option>
        <option value="su">Sundyjski - Sundanese</option>
        <option value="sw">Suahili – Kiswahili</option>
        <option value="sv">Szwedzki - svenska</option>
        <option value="tg">tadżycki - тоҷикӣ</option>
        <option value="ta">Tamilski - தமிழ்</option>
        <option value="tt">tatarski</option>
        <option value="te">telugu - తెలుగు</option>
        <option value="th">Tajski – ไทย</option>
        <option value="ti">Tygrynia - ትግርኛ</option>
        <option value="to">Tonga - lea fakatonga</option>
        <option value="tr">turecki – Türkçe</option>
        <option value="tk">Turkmeni</option>
        <option value="uk">Ukraiński – українська</option>
        <option value="ur">Urdu - اردو</option>
        <option value="ug">ujgurski</option>
        <option value="uz">uzbecki – o'zbek</option>
        <option value="vi">Wietnamski – Tiếng Việt</option>
        <option value="wa">Waloński - walon</option>
        <option value="cy">Walijski – Cymraeg</option>
        <option value="xh">Xhosa</option>
        <option value="yi">jidysz</option>
        <option value="yo">Joruba - Èdè Yorùbá</option>
        <option value="zu">Zulu - isiZulu</option>
    </select>
    @break
    @case('uk')
    <select id="known_languages" name="known_languages[]" class="form-control" data-language="uk" multiple>
        <option value="">{{ __('Виберіть або знайдіть мови...') }}</option>
        <option value="af">Afrikaans</option>
        <option value="sq">Albanian - shqip</option>
        <option value="am">Amharic - አማርኛ</option>
        <option value="ar">Arabic - العربية</option>
        <option value="an">Aragonese - aragonés</option>
        <option value="hy">Armenian - հայերեն</option>
        <option value="ast">Asturian - asturianu</option>
        <option value="az">Azerbaijani - azərbaycan dili</option>
        <option value="eu">Basque - euskara</option>
        <option value="be">Belarusian - беларуская</option>
        <option value="bn">Bengali - বাংলা</option>
        <option value="bs">Bosnian - bosanski</option>
        <option value="br">Breton - brezhoneg</option>
        <option value="bg">Bulgarian - български</option>
        <option value="ca">Catalan - català</option>
        <option value="zh">Chinese - 中文</option>
        <option value="hr">Croatian - hrvatski</option>
        <option value="cs">Czech - čeština</option>
        <option value="da">Danish - dansk</option>
        <option value="nl">Dutch - Nederlands</option>
        <option value="en">English</option>
        <option value="eo">Esperanto - esperanto</option>
        <option value="et">Estonian - eesti</option>
        <option value="fo">Faroese - føroyskt</option>
        <option value="fil">Filipino</option>
        <option value="fi">Finnish - suomi</option>

        <option value="fr">French - français</option>
        <option value="gl">Galician - galego</option>
        <option value="ka">Georgian - ქართული</option>
        <option value="de">German - Deutsch</option>
        <option value="el">Greek - Ελληνικά</option>
        <option value="gn">Guarani</option>
        <option value="gu">Gujarati - ગુજરાતી</option>
        <option value="ha">Hausa</option>
        <option value="he">Hebrew - עברית</option>
        <option value="hi">Hindi - हिन्दी</option>
        <option value="hu">Hungarian - magyar</option>
        <option value="is">Icelandic - íslenska</option>
        <option value="id">Indonesian - Indonesia</option>
        <option value="ia">Interlingua</option>
        <option value="ga">Irish - Gaeilge</option>
        <option value="it">Italian - italiano</option>
        <option value="ja">Japanese - 日本語</option>
        <option value="kn">Kannada - ಕನ್ನಡ</option>
        <option value="kk">Kazakh - қазақ тілі</option>
        <option value="km">Khmer - ខ្មែរ</option>
        <option value="ko">Korean - 한국어</option>
        <option value="ku">Kurdish - Kurdî</option>
        <option value="ky">Kyrgyz - кыргызча</option>
        <option value="lo">Lao - ລາວ</option>
        <option value="lv">Latvian - latviešu</option>

        <option value="ln">Lingala - lingála</option>
        <option value="lt">Lithuanian - lietuvių</option>
        <option value="mk">Macedonian - македонски</option>
        <option value="ms">Malay - Bahasa Melayu</option>
        <option value="ml">Malayalam - മലയാളം</option>
        <option value="mt">Maltese - Malti</option>
        <option value="mr">Marathi - मराठी</option>
        <option value="mn">Mongolian - монгол</option>
        <option value="ne">Nepali - नेपाली</option>
        <option value="no">Norwegian - norsk</option>
        <option value="or">Oriya - ଓଡ଼ିଆ</option>
        <option value="om">Oromo - Oromoo</option>
        <option value="ps">Pashto - پښتو</option>
        <option value="fa">Persian - فارسی</option>
        <option value="pl">Polish - polski</option>
        <option value="pt">Portuguese - português</option>
        <option value="pa">Punjabi - ਪੰਜਾਬੀ</option>
        <option value="qu">Quechua</option>
        <option value="ro">Romanian - română</option>
        <option value="rm">Romansh - rumantsch</option>
        <option value="ru">Russian - русский</option>
        <option value="sr">Serbian - српски</option>
        <option value="sn">Shona - chiShona</option>
        <option value="sd">Sindhi</option>
        <option value="si">Sinhala - සිංහල</option>

        <option value="sk">Slovak - slovenčina</option>
        <option value="sl">Slovenian - slovenščina</option>
        <option value="so">Somali - Soomaali</option>
        <option value="st">Southern Sotho</option>
        <option value="es">Spanish - español</option>
        <option value="su">Sundanese</option>
        <option value="sw">Swahili - Kiswahili</option>
        <option value="sv">Swedish - svenska</option>
        <option value="tg">Tajik - тоҷикӣ</option>
        <option value="ta">Tamil - தமிழ்</option>
        <option value="tt">Tatar</option>
        <option value="te">Telugu - తెలుగు</option>
        <option value="th">Thai - ไทย</option>
        <option value="ti">Tigrinya - ትግርኛ</option>
        <option value="to">Tongan - lea fakatonga</option>
        <option value="tr">Turkish - Türkçe</option>
        <option value="tk">Turkmen</option>
        <option value="uk">Ukrainian - українська</option>
        <option value="ur">Urdu - اردو</option>
        <option value="ug">Uyghur</option>
        <option value="uz">Uzbek - o‘zbek</option>

        <option value="vi">Vietnamese - Tiếng Việt</option>
        <option value="wa">Walloon - wa</option>
        <option value="cy">Welsh - Cymraeg</option>
        <option value="xh">Xhosa</option>
        <option value="yi">Yiddish</option>
        <option value="yo">Yoruba - Èdè Yorùbá</option>
        <option value="zu">Zulu - isiZulu</option>
    </select>
    @break
@endswitch
